name: Convert IPYNB to HTML and Deploy

on:
  push:
    branches:
      - main  # Cambia esto por la rama en la que quieres que se ejecute la acción

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Convert notebook to HTML
      run: |
        # Crear un directorio para los archivos HTML
        mkdir -p html_outputs
        
        # Recorrer todos los archivos .ipynb y convertirlos a HTML
        find notebooks -name '*.ipynb' | while read notebook; do
          # Obtener el directorio del notebook
          dir=$(dirname "$notebook")
          # Crear el mismo directorio en html_outputs si no existe
          mkdir -p "html_outputs/$dir"
          # Convertir el notebook a HTML y guardarlo en html_outputs
          jupyter nbconvert --to html "$notebook" --output-dir="html_outputs/$dir"
        done

        # Verificar los archivos generados
        ls -lR html_outputs  # Lista todos los archivos en html_outputs
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./ 
        publish_branch: gh-pages
        keep_files: true  # Mantener los archivos existentes en la rama gh-pages
