name: Test execution

on:
  # Se ejecuta después del despliegue de GitHub Pages
  workflow_run:
    workflows:
      - pages-build-deployment
    types:
      - completed

  # También se ejecuta cuando haya un cambio en los tests
  push:
    branches:
      - pruebas

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout target branch
      run: git checkout pruebas # Replace `main` with your target branch

    - name: Pull updated changes from source branch
      run: 
        git pull origin gh-pages # Replace `gh-pages` with your source branch

    - name: Push changes to target branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin pruebas # Push the merged changes to the target branch

    # 2. Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Run Jest tests and save results
    - name: Run Jest tests
      run: npm run test
    - name: Save Jest results
      uses: actions/upload-artifact@v3
      with:
        name: jest-results
        path: ./test-results/jest

    # 5. Run Cypress tests and save results
    - name: Run Cypress tests
      run: npm run cypress:run
    - name: Save Cypress results
      uses: actions/upload-artifact@v3
      with:
        name: cypress-results
        path: ./test-results/cypress
